In [14]:
#Import Libraries
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest, chi2, RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [4]:
#Load Data
df = pd.read_csv('Pima.csv', index_col=0)
df

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [3]:
#Define x and y

In [5]:
x = df.iloc[:,:-1]
y = df['class']

# UNivariate Selection

In [4]:
#Chi square for feature selection

In [7]:
test = SelectKBest(score_func=chi2, k = 5)
chi_score = test.fit(x,y)

In [8]:
chi_score.scores_

array([ 111.51969064, 1411.88704064,   17.60537322,   53.10803984,
       2175.56527292,  127.66934333,    5.39268155,  181.30368904])

In [11]:
x.columns

Index(['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age'], dtype='object')

In [13]:
score = pd.DataFrame(chi_score.scores_).T
score.columns = x.columns
score

preg         plas       pres      skin         test        mass  \
0  111.519691  1411.887041  17.605373  53.10804  2175.565273  127.669343   

       pedi         age  
0  5.392682  181.303689

# Recursive Feature Elimination

In [5]:
#RFE

In [16]:
lg = LogisticRegression(max_iter=500)

rfe = RFE(lg)

rfe.fit(x,y)

RFE(estimator=LogisticRegression(max_iter=500))

In [17]:
rfe.n_features_

4

In [18]:
rfe.support_

array([ True,  True, False, False, False,  True,  True, False])

In [19]:
x.columns

Index(['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age'], dtype='object')

In [ ]:
#Feature Ranking

In [20]:
rfe.ranking_

array([1, 1, 3, 5, 4, 1, 1, 2])

# Tree Based method

In [ ]:
#Tree Based method

In [21]:
dt = DecisionTreeClassifier()
dt.fit(x,y)
dt.feature_importances_

array([0.06278819, 0.32073499, 0.10712237, 0.02052284, 0.02978181,
       0.21040769, 0.12790319, 0.12073891])

In [22]:
x.columns

Index(['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age'], dtype='object')

In [ ]:
#Plasma,Mass,Pedi,Age